/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * APIドキュメント
 * OpenAPI spec version: 1
 */
import type { OrganizationProjectUsageThisMonthResponseProjectsItemUsage } from "./organizationProjectUsageThisMonthResponseProjectsItemUsage";
import type { OrganizationProjectUsageThisMonthResponseProjectsItemPerTimeUnit } from "./organizationProjectUsageThisMonthResponseProjectsItemPerTimeUnit";

export type ProjectVisibility = "organization" | "personal" | "team";

export type OrganizationProjectUsageThisMonthResponseProjectsItem = {
  projectID: string;
  projectName: string;
  visibility: ProjectVisibility;
  usage: OrganizationProjectUsageThisMonthResponseProjectsItemUsage;
  /** 集計単位 */
  perTimeUnit: OrganizationProjectUsageThisMonthResponseProjectsItemPerTimeUnit;
  from: string;
  to: string;
};
